spring.application.name=EcommerceProduct
server.port=4300
# Oracle DB settings
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=hello
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JSP settings
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
